import { DM_Mono, Geist_Mono, Cascadia_Mono , Fragment_Mono, Cutive_Mono, Inter  } from "next/font/google";
import "./globals.css";

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const dmMono = DM_Mono({
  subsets: ['latin'],
  weight:['400'],
  variable:'--font-dm-mono',
});
const GeistMono = Geist_Mono({
  subsets: ['latin'],
  weight:['300', '400', '500'],
  variable:'--font-geist-mono',
});
const cascadiaMono = Cascadia_Mono({
  subsets: ['latin'],
  weight:['300', '400', '500'],
  variable:'--font-cascadia-mono',
});
const fragmentMono = Fragment_Mono({
  subsets: ['latin'],
  weight:[ '400'],
  variable:'--font-fragment-mono',
});

const cultiveMono = Cutive_Mono ({
  subsets: ['latin'],
  weight:['400'],
  variable:'--font-cutive-mono',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${dmMono.variable}${GeistMono.variable}${cascadiaMono.variable}${fragmentMono.variable}${cultiveMono.variable}`}>
        <NextIntlClientProvider messages={messages}>
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
